WebApplicationNET6/Pages/Categories/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplicationNET6.Data;
using WebApplicationNET6.Model;

namespace WebApplicationNET6.Pages.Categories
{
    public class CreateModel : PageModel
    {
        private readonly WebApplicationNET6.Data.BlogDBContext _context;

        public CreateModel(WebApplicationNET6.Data.BlogDBContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Category Category { get; set; }
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Category.Add(Category);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WebApplicationNET6/Pages/CategoryAndUser/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplicationNET6.Model;

namespace WebApplicationNET6.Pages.CategoryAndUser
{
    public class CreateModel : PageModel
    {
        private readonly WebApplicationNET6.Data.BlogDBContext _context;

        public CreateModel(WebApplicationNET6.Data.BlogDBContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Category Category { get; set; }
        [BindProperty]
        public User User { get; set; }


        [HttpPost]
        public async Task<IActionResult> OnPostCreateCategoryAsync()
        {
            //if (!ModelState.IsValid)
            if (!IsValidCategoryModel())
            {
                return Page();
            }
            else
            {
                //Meta data
                Category.CreateDate = DateTime.UtcNow;
                Category.UpdateDate = DateTime.UtcNow;
                Category.CreateUserId = 1; //Login => userId

                _context.Category.Add(Category);
                await _context.SaveChangesAsync();
                return RedirectToPage("./Index");
            }

        }
        [HttpPost]
        public async Task<IActionResult> OnPostCreateUserAsync()
        {

            if (User == null)
            {
                return Page();
            }
            else
            {
                _context.User.Add(User);
                await _context.SaveChangesAsync();
                return RedirectToPage("./IndexUser");
            }

        }

        private bool IsValidCategoryModel()
        {
            if(String.IsNullOrWhiteSpace(Category.Title))
                return false;
            //

            return true;
        }
    }
}

WebApplicationNET6/Pages/CategoryAndUser/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplicationNET6.Model;

namespace WebApplicationNET6.Pages.CategoryAndUser
{
    public class IndexModel : PageModel
    {
        private readonly WebApplicationNET6.Data.BlogDBContext _context;

        public IndexModel(WebApplicationNET6.Data.BlogDBContext context)
        {
            _context = context;
        }

        public List<Category> Category { get; set; } = default!;

        public async Task OnGetAsync()
        {
            if (_context.Category != null)
            {
                Category = await _context.Category.ToListAsync();
            }
        }
    }
}

WebApplicationNET6/Pages/CategoryAndUser/IndexUser.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplicationNET6.Model;

namespace WebApplicationNET6.Pages.CategoryAndUser
{
    public class IndexUserModel : PageModel
    {
        private readonly WebApplicationNET6.Data.BlogDBContext _context;

        public IndexUserModel(WebApplicationNET6.Data.BlogDBContext context)
        {
            _context = context;
        }

        public List<User> User { get; set; } = default!;

        public async Task OnGetAsync()
        {
            if (_context.Category != null)
            {
                User = await _context.User.ToListAsync();
            }
        }
    }
}

WebApplicationNET6/Pages/CategoryAndUser/Create.cshtml
@page
@model WebApplicationNET6.Pages.CategoryAndUser.CreateModel
@{
}
<h1>Create</h1>

<h4>Category</h4>
<hr />
<form class="form" method="post">
    <ng-form method="post">   
            <div class="form-group">
                <label asp-for="Category.Title" class="control-label"></label>
                <input asp-for="Category.Title" class="form-control" />
                <span asp-validation-for="Category.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category.Content" class="control-label"></label>
                <input asp-for="Category.Content" class="form-control" />
                <span asp-validation-for="Category.Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category.CreateUserId" class="control-label"></label>
                <input asp-for="Category.CreateUserId" class="form-control" />
                <span asp-validation-for="Category.CreateUserId" class="text-danger"></span>
            </div>
@*            <div class="form-group" class="col-md-4" >
                <label asp-for="Category.CreateDate" class="control-label"></label>
                <input asp-for="Category.CreateDate" class="form-control" />
                <span asp-validation-for="Category.CreateDate" class="text-danger"></span>
            </div>*@
@*            <div class="form-group" >
                <label asp-for="Category.UpdateUserId" class="control-label"></label>
                <input asp-for="Category.UpdateUserId" class="form-control" />
                <span asp-validation-for="Category.UpdateUserId" class="text-danger"></span>
            </div>*@
@*            <div class="form-group">
                <label asp-for="Category.UpdateDate" class="control-label"></label>
                <input asp-for="Category.UpdateDate" class="form-control" />
                <span asp-validation-for="Category.UpdateDate" class="text-danger"></span>
            </div>*@
           
            <input type="submit" value="Create Category" class="btn btn-primary"asp-page-handler="CreateCategory"/>
</ng-form>
<ng-form>  
            <div class="form-group">
                <label asp-for="User.Name" class="control-label"></label>
                <input asp-for="User.Name" class="form-control" />
                <span asp-validation-for="User.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="User.Phone" class="control-label"></label>
                <input asp-for="User.Phone" class="form-control" />
                <span asp-validation-for="User.Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="User.Email" class="control-label"></label>
                <input asp-for="User.Email" class="form-control" />
                <span asp-validation-for="User.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="User.Password" class="control-label"></label>
                <input asp-for="User.Password" class="form-control" />
                <span asp-validation-for="User.Password" class="text-danger"></span>
            </div>

            <input type="submit" value="Create User" class="btn btn-primary" asp-page-handler="CreateUser"/>
        </ng-form>
   
</form>

WebApplicationNET6/Pages/CategoryAndUser/Index.cshtml
@page
@model WebApplicationNET6.Pages.CategoryAndUser.IndexModel
@{
}
 <h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Category[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category[0].Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category[0].CreateUserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category[0].CreateDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category[0].UpdateUserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category[0].UpdateDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Category) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateUserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdateUserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdateDate)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebApplicationNET6/Pages/CategoryAndUser/IndexUser.cshtml
@page
@model WebApplicationNET6.Pages.CategoryAndUser.IndexUserModel
@{
}

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.User[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User[0].Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User[0].Email)
            </th>
            <th>
               @Html.DisplayNameFor(model => model.User[0].Password)
            </th>
        
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.User) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            
        
        </tr>
}
    </tbody>
</table>